# Generated by Django 3.0.4 on 2020-03-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('small_text', models.CharField(db_index=True, max_length=150)),
                ('body', models.TextField(blank=True, db_index=True)),
            ],
        ),
    ]
