# Generated by Django 3.0.4 on 2020-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0002_about_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slug',
            field=models.SlugField(default='about', editable=False, max_length=10, unique=True),
        ),
    ]
