# Generated by Django 3.0.4 on 2020-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0003_auto_20200315_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
