# Generated by Django 3.0.4 on 2020-03-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='data_filter',
            field=models.CharField(default='*', max_length=20, unique=True),
        ),
    ]
