# Generated by Django 3.0.4 on 2020-03-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0006_auto_20200315_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='data_filter',
        ),
    ]
