# Generated by Django 3.0.4 on 2020-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0007_remove_services_data_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='data_filter',
            field=models.CharField(default='*', max_length=20),
        ),
    ]
