# Generated by Django 3.0.4 on 2020-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0008_services_data_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='data_filter',
            field=models.CharField(choices=[('*', '*'), ('.building', '.building'), ('.webdesign', '.webdesign'), ('.adversting', '.adversting'), ('.painting', '.painting')], max_length=20),
        ),
    ]
