# Generated by Django 3.0.4 on 2020-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0010_auto_20200315_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icons',
            field=models.CharField(choices=[('fa-wrench', 'fa-wrench'), ('fa-cogs', 'fa-cogs'), ('fa-cog', 'fa-cog'), ('fa-heart', 'fa-heart'), ('fa-paint-brush', 'fa-paint-brush')], default='fa fa-wrench', max_length=20),
        ),
    ]
