# Generated by Django 3.0.4 on 2020-03-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0012_auto_20200315_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('image', models.ImageField(upload_to='uploads/portfolio')),
                ('date', models.DateField()),
            ],
        ),
    ]
