# Generated by Django 3.0.4 on 2020-03-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0013_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
