# Generated by Django 3.0.4 on 2020-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0017_auto_20200316_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/portfolio/base'),
        ),
    ]
