# Generated by Django 3.0.4 on 2020-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0019_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(db_index=True, max_length=250)),
                ('phone', models.CharField(db_index=True, max_length=250)),
                ('email', models.EmailField(db_index=True, max_length=250)),
            ],
        ),
    ]
