# Generated by Django 3.0.4 on 2020-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0022_auto_20200317_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default=1, editable=False, max_length=1),
        ),
    ]
