# Generated by Django 3.0.4 on 2020-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinsaat', '0023_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
